### ISSUE TITLE
STL files?

### ISSUE THREAD

**Issue by wa2mze** [strayr/stealthburner_revo-cr#1]
I have an Ender 3 PRO that is already upgraded to a Revo CR.
I plan on doing a Swiltchwire conversion on it.
So, I could test this, but I'd need STL files to print.

**Comment by strayr** [comment]
I'll see about extracting from the fusion model and uploading.

**Comment by strayr** [comment]
they're in the folder MESH becasue an STL is a kind of mesh file.

You may also want this mount https://github.com/strayr/voron-afterburner-ender3

I have only made STLs for parts that I have changed, so get the rest of the parts from the official voron repos.

**Comment by strayr** [comment]
Updated README.md to reflect loction of STLs
